### ISSUE TITLE
Implement an optional hardcore-yolo mode that tries to update the db-name in `database.yml`

### ISSUE THREAD

**Issue by A5308Y** [rmehner/uff_db_loader#20]

**Comment by rmehner** [comment]
For that, we'd need to find a way to replace the database name in place, without touching the format of the YAML file (and losing comments and stuff).

**Comment by A5308Y** [comment]
I was thinking of a potentially destructive way of doing it with enough warnings up front. Maybe just a regex replacing the first line after development containing the word "database". Or having template with a placeholder for the development db name. 

We still have the old version in git and never check in the changes of the db name anyway. At least for act.

**Comment by rmehner** [comment]
Maybe we can see if there's a tool like https://github.com/ceejbot/tomato, but for YAML.

**Comment by A5308Y** [comment]
I wanted to start with psych and then use regex as a fallback. Can psych not edit in place?

**Comment by A5308Y** [comment]
Ah. People on the internet are claiming it's impossible.
