### ISSUE TITLE
Allow restore of currently active db

### ISSUE THREAD

**Issue by A5308Y** [rmehner/uff_db_loader#59]
If I try to use `bin/rails uff_db_loader:restore` with the currently active database I get:

```sh
rails aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database


Caused by:
PG::ObjectInUse: ERROR:  cannot drop the currently open database

Tasks: TOP => uff_db_loader:restore
(See full trace by running task with --trace)
```

But oftentimes I want to reset the current database to the downloaded version to test a newly written migration again, so that's exactly my use case. As a workaround I use `bin/rails uff_db_loader:switch` followed by `bin/rails uff_db_loader:restore`. It would be nice if I didn't have to do the additional step.

**Comment by rmehner** [comment]
Fixed with #62
