### ISSUE TITLE
Order selectable databases by creation date

### ISSUE THREAD

**Issue by A5308Y** [rmehner/uff_db_loader#60]
If I have a couple of databases it's not always easy to find the one I want to use. It's almost always the one created last of a specific environment. uff_db_loader could order the list like this:
```
- latest_production
- latest_staging
{all others by created at}
```
or just sort everything by created at, because that might be easier to understand.

**Comment by rmehner** [comment]
This might be a good and simple solution to get most of the use cases covered for #55
